var countryCodes = {
     "Afghanistan": "AF",
     "Albania": "AL",
     "Algeria": "DZ",
     "Andorra": "AD",
     "Angola": "AO",
     "Antigua": "AG",
     "Antilles": "AN",
     "Barbuda": "AG",
     "Argentina": "AR",
     "Armenia": "AM",
     "Aruba": "AW",
     "Australia": "AU",
     "Austria": "AT",
     "Azerbaijan": "AZ",
     "Bahamas": "BS",
     "Bahrain": "BH",
     "Bangladesh": "BD",
     "Barbados": "BB",
     "Belarus": "BY",
     "Belgium": "BE",
     "Belize": "BZ",
     "Benin": "BJ",
     "Bermuda": "BM",
     "Bhutan": "BT",
     "Bolivia": "BO",
     "Bosnia": "BA",
     "Herzegovina": "BA",
     "Bissau": "GW",
     "Botswana": "BW",
     "Brazil": "BR",
     "Brunei": "BN",
     "Bulgaria": "BG",
     "Burkina Faso": "BF",
     "Burundi": "BI",
     "Cambodia": "KH",
     "Cameroon": "CM",
     "Canada": "CA",
     "Cape Verde": "CV",
     "Cayman Islands": "KY",
     "Central African Republic": "CF",
     "Chad": "TD",
     "Chile": "CL",
     "China": "CN",
     "Colombia": "CO",
     "Comoros": "KM",
     "Congo": "CG",
     "Costa Rica": "CR",
     "Cote dIvoire": "CI",
     "Croatia": "HR",
     "Cuba": "CU",
     "Cyprus": "CY",
     "Czech Republic": "CZ",
     "Czechia": "CZ",
     "Denmark": "DK",
     "Djibouti": "DJ",
     "Dominica": "DM",
     "Dominican Republic": "DO",
     "Ecuador": "EC",
     "Egypt": "EG",
     "El Salvador": "SV",
     "Equatorial Guinea": "GQ",
     "Eritrea": "ER",
     "Estonia": "EE",
     "Ethiopia": "ET",
     "Falkland Islands": "FK",
     "Fiji": "FJ",
     "Finland": "FI",
     "France": "FR",
     "French Guiana": "GF",
     "French Polynesia": "PF",
     "Gabon": "GA",
     "Gambia": "GM",
     "Georgia": "GE",
     "Germany": "DE",
     "Ghana": "GH",
     "Greece": "GR",
     "Greenland": "GL",
     "Grenada": "GD",
     "Grenadines": "VC",
     "Guam": "GU",
     "Guatemala": "GT",
     "Guinea": "GN",
     "Guinea-Bissau": "GW",
     "Guyana": "GY",
     "Haiti": "HT",
     "Holy See": "VA",
     "Honduras": "HN",
     "Hong Kong": "HK",
     "Hungary": "HU",
     "Iceland": "IS",
     "India": "IN",
     "Indonesia": "ID",
     "Iran": "IR",
     "Iraq": "IQ",
     "Ireland": "IE",
     "Israel": "IL",
     "Italy": "IT",
     "Jamaica": "JM",
     "Japan": "JP",
     "Jordan": "JO",
     "Kazakhstan": "KZ",
     "Kenya": "KE",
     "Kiribati": "KI",
     "Kuwait": "KW",
     "Kyrgyzstan": "KG",
     "Laos": "LA",
     "Latvia": "LV",
     "Lebanon": "LB",
     "Lesotho": "LS",
     "Liberia": "LR",
     "Libya": "LY",
     "Liechtenstein": "LI",
     "Lithuania": "LT",
     "Luxembourg": "LU",
     "Macau": "MO",
     "Macedonia": "MK",
     "Madagascar": "MG",
     "Malawi": "MW",
     "Malaysia": "MY",
     "Maldives": "MV",
     "Mali": "ML",
     "Malta": "MT",
     "Mariana Islands": "MP",
     "Marshall Islands": "MH",
     "Martinique": "MQ",
     "Mauritania": "MR",
     "Mauritius": "MU",
     "Mayotte": "YT",
     "Mexico": "MX",
     "Micronesia": "FM",
     "Moldova": "MD",
     "Monaco": "MC",
     "Mongolia": "MN",
     "Montenegro": "ME",
     "Morocco": "MA",
     "Mozambique": "MZ",
     "Myanmar": "MM",
     "Namibia": "NA",
     "Nauru": "NR",
     "Nepal": "NP",
     "Netherlands": "NL",
     "New Caledonia": "NC",
     "New Zealand": "NZ",
     "Nicaragua": "NI",
     "Niger": "NE",
     "Nigeria": "NG",
     "North Korea": "KP",
     "Norway": "NO",
     "Oman": "OM",
     "Pakistan": "PK",
     "Palau": "PW",
     "Palestine": "PS",
     "Panama": "PA",
     "Papua New Guinea": "PG",
     "Paraguay": "PY",
     "Peru": "PE",
     "Philippines": "PH",
     "Poland": "PL",
     "Polynesia": "PF",
     "Portugal": "PT",
     "Puerto Rico": "PR",
     "Qatar": "QA",
     "Reunion": "RE",
     "Romania": "RO",
     "Russia": "RU",
     "Rwanda": "RW",
     "Saint Barthelemy": "BL",
     "Saint Helena": "SH",
     "Saint Kitts": "KN",
     "Saint Lucia": "LC",
     "Saint Martin": "MF",
     "Saint Vincent": "VC",
     "Samoa": "WS",
     "San Marino": "SM",
     "Sao Tome": "ST",
     "Saudi Arabia": "SA",
     "Senegal": "SN",
     "Serbia": "RS",
     "Seychelles": "SC",
     "Sierra Leone": "SL",
     "Singapore": "SG",
     "Slovakia": "SK",
     "Slovenia": "SI",
     "Solomon Islands": "SB",
     "Somalia": "SO",
     "South Africa": "ZA",
     "South Korea": "KR",
     "South Sudan": "SS",
     "Spain": "ES",
     "Sri Lanka": "LK",
     "Sudan": "SD",
     "Suriname": "SR",
     "Swaziland": "SZ",
     "Sweden": "SE",
     "Switzerland": "CH",
     "Syria": "SY",
     "Taiwan": "TW",
     "Tajikistan": "TJ",
     "Tanzania": "TZ",
     "Thailand": "TH",
     "Timor-Leste": "TL",
     "Togo": "TG",
     "Tonga": "TO",
     "Trinidad-Tobago": "TT",
     "Tunisia": "TN",
     "Turkey": "TR",
     "Turkmenistan": "TM",
     "Turks and Caicos": "TC",
     "Tuvalu": "TV",
     "Uganda": "UG",
     "Ukraine": "UA",
     "United Arab Emirates": "AE",
     "United Kingdom": "GB",
     "United States": "US",
     "Uruguay": "UY",
     "Uzbekistan": "UZ",
     "Vanuatu": "VU",
     "Venezuela": "VE",
     "Vietnam": "VN",
     "Virgin Islands": "VI",
     "Western Sahara": "EH",
     "Yemen": "YE",
     "Zambia": "ZM",
     "Zimbabwe": "ZW",
     "AK": "US",
     "AL": "US",
     "AZ": "US",
     "AR": "US",
     "CA": "US",
     "CO": "US",
     "CT": "US",
     "DE": "US",
     "FL": "US",
     "GA": "US",
     "HI": "US",
     "ID": "US",
     "IL": "US",
     "IN": "US",
     "IA": "US",
     "KS": "US",
     "KY": "US",
     "LA": "US",
     "ME": "US",
     "MD": "US",
     "MA": "US",
     "MI": "US",
     "MN": "US",
     "MS": "US",
     "MO": "US",
     "MT": "US",
     "NE": "US",
     "NV": "US",
     "NH": "US",
     "NJ": "US",
     "NM": "US",
     "NY": "US",
     "NC": "US",
     "ND": "US",
     "OH": "US",
     "OK": "US",
     "OR": "US",
     "PA": "US",
     "RI": "US",
     "SC": "US",
     "SD": "US",
     "TN": "US",
     "TX": "US",
     "UT": "US",
     "VT": "US",
     "VA": "US",
     "WA": "US",
     "WV": "US",
     "WI": "US",
     "WY": "US",
     "Alaska": "US",
     "Alabama": "US",
     "Arizona": "US",
     "Arkansas": "US",
     "California": "US",
     "Colorado": "US",
     "Connecticut": "US",
     "Delaware": "US",
     "Florida": "US",
     "Georgia": "US",
     "Hawaii": "US",
     "Idaho": "US",
     "Illinois": "US",
     "Indiana": "US",
     "Iowa": "US",
     "Kansas": "US",
     "Kentucky": "US",
     "Louisiana": "US",
     "Maine": "US",
     "Maryland": "US",
     "Massachusetts": "US",
     "Michigan": "US",
     "Minnesota": "US",
     "Mississippi": "US",
     "Missouri": "US",
     "Montana": "US",
     "Nebraska": "US",
     "Nevada": "US",
     "New Hampshire": "US",
     "New Jersey": "US",
     "New Mexico": "US",
     "New York": "US",
     "North Carolina": "US",
     "North Dakota": "US",
     "Ohio": "US",
     "Oklahoma": "US",
     "Oregon": "US",
     "Pennsylvania": "US",
     "Rhode Island": "US",
     "South Carolina": "US",
     "South Dakota": "US",
     "Tennessee": "US",
     "Texas": "US",
     "Utah": "US",
     "Vermont": "US",
     "Virginia": "US",
     "Washington": "US",
     "West Virginia": "US",
     "Wisconsin": "US",
     "Wyoming": "US"
   }
   module.exports = countryCodes;